# Use official Node.js image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the rest of the app
COPY . .

# Expose port
EXPOSE 4545

# Start the app in development mode
CMD ["yarn", "dev", "--hostname", "0.0.0.0", "--port", "4545"] 