services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: survey_backend_prod
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=False
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: survey_frontend_prod
    ports:
      - "4545:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
