services:
  - type: web
    name: survey-backend
    env: python
    buildCommand: |
      echo "=== BUILD START ==="
      pip install -r requirements.txt
      echo "=== DEPENDENCIES INSTALLED ==="
      python manage.py collectstatic --noinput
      echo "=== STATIC FILES COLLECTED ==="
      python manage.py showmigrations
      echo "=== MIGRATIONS SHOWN ==="
      python manage.py migrate --noinput --verbosity=2
      echo "=== MIGRATIONS COMPLETED ==="
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: survey-backend.onrender.com
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_DEBUG
        value: "False"
    plan: free
