services:
  - type: web
    name: survey-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate --noinput && \
      python manage.py create_superuser
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: survey-concierge.onrender.com,localhost,127.0.0.1,0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        sync: false
    plan: free
