# Generated by Django 4.2.23 on 2025-09-04 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('survey', '0001_initial'), ('survey', '0002_question_section_title'), ('survey', '0003_question_subfields_alter_question_question_type'), ('survey', '0004_question_columns_question_rows_and_more'), ('survey', '0005_alter_question_question_type'), ('survey', '0006_alter_questionresponse_answer_type'), ('survey', '0007_survey_concierge_logo_url_survey_logo_url'), ('survey', '0008_question_is_ordinal_alter_survey_logo_url'), ('survey', '0009_remove_question_is_ordinal_question_is_dropdown'), ('survey', '0010_alter_question_question_type_and_more'), ('survey', '0011_question_scale_exclusions_question_scale_options'), ('survey', '0012_remove_question_question_type_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('concierge_logo_url', models.URLField(blank=True, help_text='URL to the Survey Concierge logo for this survey', null=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to the logo for this survey', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('subfields', models.JSONField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, null=True)),
                ('rows', models.JSONField(blank=True, null=True)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('primary_type', models.CharField(choices=[('open_text', 'Open Text'), ('form', 'Form'), ('grid', 'Grid')], default='open_text', max_length=50)),
                ('randomize_options', models.BooleanField(default=False)),
                ('secondary_type', models.CharField(default='text', max_length=50)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField()),
                ('answer_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='survey.surveyresponse')),
            ],
            options={
                'unique_together': {('survey_response', 'question')},
            },
        ),
    ]
