# Generated by Django 4.2.23 on 2025-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
