# Generated by Django 4.2.23 on 2025-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_question_subfields_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rows',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('rating', 'Rating'), ('email', 'Email'), ('number', 'Number'), ('matrix', 'Matrix'), ('cross_matrix', 'Cross Matrix')], default='text', max_length=20),
        ),
    ]
