# Generated by Django 4.2.23 on 2025-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_columns_question_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('rating', 'Rating'), ('email', 'Email'), ('number', 'Number'), ('matrix', 'Matrix'), ('cross_matrix', 'Cross Matrix'), ('cross_matrix_checkbox', 'Cross Matrix Checkbox')], default='text', max_length=100),
        ),
    ]
