# Generated by Django 4.2.23 on 2025-08-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_questionresponse_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='concierge_logo_url',
            field=models.URLField(blank=True, help_text='URL to the Survey Concierge logo for this survey', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to the TAF logo for this survey', null=True),
        ),
    ]
