# Generated by Django 4.2.23 on 2025-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_concierge_logo_url_survey_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_ordinal',
            field=models.BooleanField(default=False, help_text='For multiple choice questions, use dropdown instead of radio buttons if options are ordinal/linear'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to the logo for this survey', null=True),
        ),
    ]
