# Generated by Django 4.2.23 on 2025-08-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_question_is_ordinal_alter_survey_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_ordinal',
        ),
        migrations.AddField(
            model_name='question',
            name='is_dropdown',
            field=models.BooleanField(default=False, help_text='For multiple choice questions, use dropdown instead of radio buttons'),
        ),
    ]
