# Generated by Django 4.2.23 on 2025-09-02 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0009_remove_question_is_ordinal_question_is_dropdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("multiple_choice", "Multiple Choice"),
                    ("checkbox", "Checkbox"),
                    ("rating", "Rating"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("matrix", "Matrix"),
                    ("cross_matrix", "Cross Matrix"),
                    ("cross_matrix_checkbox", "Cross Matrix Checkbox"),
                    ("scale", "Scale"),
                ],
                default="text",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="questionresponse",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
