# Generated by Django 4.2.23 on 2025-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0010_alter_question_question_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="scale_exclusions",
            field=models.JSONField(
                blank=True,
                help_text="For scale questions: list of exclusion options (e.g., ['Not applicable', 'Don't know', 'Did not recruit'])",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="scale_options",
            field=models.JSONField(
                blank=True,
                help_text="For scale questions: list of scale options (e.g., ['Much harder', 'Harder', 'Same', 'Easier', 'Much easier'])",
                null=True,
            ),
        ),
    ]
