# Generated by Django 4.2.23 on 2025-09-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_question_scale_exclusions_question_scale_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_exclusions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_options',
        ),
        migrations.AddField(
            model_name='question',
            name='primary_type',
            field=models.CharField(choices=[('open_text', 'Open Text'), ('form', 'Form'), ('grid', 'Grid')], default='open_text', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='randomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='secondary_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
    ]
