# Generated by Django 4.2.23 on 2025-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial_squashed_0012_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='logo_url',
            field=models.CharField(blank=True, help_text='URL to the logo for this survey', max_length=200, null=True),
        ),
    ]
