# Generated by Django 4.2.23 on 2025-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_alter_survey_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='secondary_type',
            field=models.CharField(choices=[], default='text', max_length=50),
        ),
    ]
