# Generated by Django 4.2.23 on 2025-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0014_alter_question_secondary_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="secondary_type",
            field=models.CharField(default="text", max_length=50),
        ),
    ]
