# Generated by Django 4.2.23 on 2025-09-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0015_alter_question_secondary_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_dropdown",
        ),
    ]
