# Generated by Django 4.2.23 on 2025-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_remove_is_dropdown_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_none_option',
            field=models.BooleanField(default=False, help_text='Add "None of the Above" option (always appears last)'),
        ),
        migrations.AddField(
            model_name='question',
            name='has_other_option',
            field=models.BooleanField(default=False, help_text='Add "Other (please specify)" option with text input'),
        ),
    ]
