# Generated by Django 4.2.23 on 2025-09-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_question_has_none_option_question_has_other_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subfield_validations',
            field=models.JSONField(blank=True, help_text='Validation rules for each subfield: {"field_name": {"type": "positive_number|negative_number|email|text", "required": true}}', null=True),
        ),
    ]
