# Generated by Django 4.2.23 on 2025-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0019_add_row_count_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="row_count",
            field=models.IntegerField(
                default=1, help_text="Number of rows for text questions"
            ),
        ),
    ]
