# Generated by Django 4.2.23 on 2025-09-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0020_alter_question_row_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="other_option_label",
            field=models.CharField(
                blank=True,
                help_text='Custom label for "Other" text input (e.g., "Please specify details")',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="other_option_rows",
            field=models.IntegerField(
                default=1, help_text='Number of text rows for "Other" option (1-5)'
            ),
        ),
    ]
