# Generated by Django 4.2.23 on 2025-09-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0021_add_other_option_customization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="other_option_label",
        ),
        migrations.RemoveField(
            model_name="question",
            name="other_option_rows",
        ),
        migrations.AddField(
            model_name="question",
            name="comment_box_label",
            field=models.CharField(
                blank=True,
                help_text='Custom label for comment box (e.g., "Additional comments")',
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="comment_box_rows",
            field=models.IntegerField(
                default=3, help_text="Number of rows for comment box (1-10)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="has_comment_box",
            field=models.BooleanField(
                default=False,
                help_text="Add a separate comment box for additional notes",
            ),
        ),
    ]
