# Generated by Django 4.2.23 on 2025-09-12 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0022_add_comment_box_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="store_on_next",
            field=models.BooleanField(
                default=False,
                help_text="Store this question's answer when user clicks Next (only works if survey has store_basic_details enabled)",
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="store_basic_details",
            field=models.BooleanField(
                default=False,
                help_text="Enable storing basic details (like email) when users click Next on specific questions",
            ),
        ),
        migrations.CreateModel(
            name="PartialSurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer", models.JSONField()),
                ("answer_type", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.question",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partial_responses",
                        to="survey.survey",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["survey", "ip_address"],
                        name="survey_part_survey__a12912_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="survey_part_created_305530_idx"
                    ),
                ],
                "unique_together": {("survey", "question", "ip_address")},
            },
        ),
    ]
