# Generated by Django 4.2.23 on 2025-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0023_question_store_on_next_survey_store_basic_details_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="partialsurveyresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="partialsurveyresponse",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="True if this partial response was converted to a complete survey response",
            ),
        ),
        migrations.AddField(
            model_name="partialsurveyresponse",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Browser session ID to track user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partialsurveyresponse",
            unique_together={("survey", "question", "ip_address", "session_id")},
        ),
        migrations.AddIndex(
            model_name="partialsurveyresponse",
            index=models.Index(
                fields=["survey", "session_id"], name="survey_part_survey__b02845_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partialsurveyresponse",
            index=models.Index(
                fields=["is_completed"], name="survey_part_is_comp_3054e6_idx"
            ),
        ),
    ]
