# Generated by Django 4.2.23 on 2025-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_alter_partialsurveyresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exclusive_column',
            field=models.CharField(blank=True, help_text='Column name that should be exclusive (only one option can be selected per row)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='none_option_text',
            field=models.CharField(blank=True, help_text='Custom text for "None of the Above" option (defaults to "None of the Above" if empty)', max_length=200, null=True),
        ),
    ]
