# Generated by Django 4.2.23 on 2025-09-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_question_exclusive_column_question_none_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment_box_label',
            field=models.CharField(blank=True, help_text='Custom label for comment box (e.g., "Additional comments")', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='exclusive_column',
            field=models.CharField(blank=True, help_text='Column name that should be exclusive (only one option can be selected per row)', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='none_option_text',
            field=models.CharField(blank=True, help_text='Custom text for "None of the Above" option (defaults to "None of the Above" if empty)', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section_title',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
