# Generated by Django 4.2.23 on 2025-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_update_slider_default_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment_box_trigger_value',
            field=models.CharField(blank=True, help_text='Only show comment box when this answer is selected (e.g., "Yes"). Leave blank to always show comment box.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_none_option',
            field=models.BooleanField(default=False, help_text='Add "None of the above" option (always appears last)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='none_option_text',
            field=models.CharField(blank=True, help_text='Custom text for "None of the above" option (defaults to "None of the above" if empty)', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='primary_type',
            field=models.CharField(choices=[('open_text', 'Open Text'), ('form', 'Form'), ('scale', 'Scale/Rating'), ('grid', 'Grid')], default='open_text', max_length=50),
        ),
    ]
