# Generated by Django 4.2.23 on 2025-10-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_question_comment_box_trigger_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='thank_you_message',
            field=models.TextField(blank=True, help_text='Custom thank you message shown after survey submission. Leave blank for default message.', null=True),
        ),
    ]
