# Generated by Django 4.2.23 on 2025-10-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_survey_thank_you_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='randomize_columns',
            field=models.BooleanField(default=False, help_text='Randomize the order of columns in grid questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='randomize_rows',
            field=models.BooleanField(default=False, help_text='Randomize the order of rows in grid questions'),
        ),
    ]
